MesoOn/Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MesoOn/blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

MesoOn/courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, krijo_klase, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim')
]

MesoOn/users/urls.py
from django.urls import path

from users.views import Profile, kerkesa

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', kerkesa, name='kerkesa')

]

MesoOn/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Header</a>
      <span>Page</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-primary'>Welcome!</h1>
		    <h2>Learn more about us</h2>
		    <hr>
		    <p>Welcome to cybo dev ethio, where education meets collaboration in the world of technology and cybersecurity. Here's the project for INSA gradution
At cybo dev ethio, we're more than just an online learning platform; we're a community of passionate individuals united by our love for technology and cybersecurity. Join us on this exciting journey of learning, growth, and collaboration.
we're passionate about empowering individuals to expand their knowledge and skills in the ever-evolving fields of technology and cybersecurity.</p>
		    <p>ወደ cybo-dev ኢትዮ እንኳን በደህና መጡ፣ ትምህርት በቴክኖሎጂ እና በሳይበር ደህንነት ዓለም ውስጥ ትብብርን ወደ ሚገናኝበት። የ INSA ምረቃ ፕሮጀክት ይኸውና በሳይቦ ዴቭ ኢትዮ፣ እኛ ከኦንላይን የመማሪያ መድረክ በላይ ነን። ለቴክኖሎጂ እና ለሳይበር ደህንነት  ያላቸው ግለሰቦች ማህበረሰብ ነን። በዚህ አስደሳች የመማር፣ የእድገት እና የትብብር ጉዞ ላይ ይቀላቀሉን። ግለሰቦች እውቀታቸውን እና ክህሎቶቻቸውን በየጊዜው በማደግ ላይ ባሉ የቴክኖሎጂ እና የሳይበር ደህንነት መስኮች ለማበረታታት እንወዳለን።.</p>
		    <button type="button" class="btn btn-primary">Let's Know More</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

MesoOn/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>AKa.com</title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
		<div class="container">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/logo.png' %}" alt=""></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
	
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}">Header</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset">Courses</a>
				  </li>
			  </li>
			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_klase' %}">Create Classes</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_lende' %}">Create Classes</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_mesim' %}">Create Classes</a>
			  </li>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Contact</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">About Us</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:post_list' %}">Share Idea</a>
			  </li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  
			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>
			  
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Sign In</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Sign up</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Join our community!</h2>
				<p>የሳይበር ደህንነት መሰረታዊ ነገሮች፡ የሳይበር ደህንነት መሰረታዊ ነገሮችን ይወቁ፣ ማስፈራሪያን መለየት፣ የአደጋ ግምገማ እና የእርስዎን ዲጂታል ንብረቶች ለመጠበቅ ምርጥ ልምዶችን ጨምሮ።

የበይነመረብ ደህንነት፡ እንዴት ድሩን በደህና ማሰስ እንደሚችሉ፣ የአስጋሪ ሙከራዎችን መለየት እና የመስመር ላይ መለያዎችዎን ደህንነት ይጠብቁ።

የውሂብ ግላዊነት፡ የውሂብ ግላዊነትን፣ ምስጠራን እና የእርስዎን የግል መረጃ ከጊዜ ወደ ጊዜ በተገናኘ ዓለም ውስጥ እንዴት መጠበቅ እንደሚችሉ ይረዱ።

ደህንነቱ የተጠበቀ የኮድ አሰራር፡ ለገንቢዎች፣ ኮርሶቻችን ደህንነቱ የተጠበቀ ኮድ ለመፃፍ እና የተለመዱ ተጋላጭነቶችን ለመለየት ግንዛቤዎችን ይሰጣሉ።

የአውታረ መረብ ደህንነት፡ ፋየርዎል፣ ቪፒኤን እና የጣልቃ መገኘትን ጨምሮ የአውታረ መረብ ደህንነት አስፈላጊ ነገሮችን ያስሱ።

የአደጋ ምላሽ፡ ለሳይበር አደጋዎች እንዴት ውጤታማ ምላሽ መስጠት እንደሚችሉ ይወቁ እና ይቀንሱ: </p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Register now</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Contact Information</h4>
						<ul class="contact-list">
							<li>Akrem <br>Kibrachew</li>
							<li>+2519877822</li>
							<li>coder.phymnan@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Cource</h4>
						<ul>
							<li><a href="">Network Security</a></li>
							<li><a href="">Information Security</a></li>
							<li><a href="">Cryptography</a></li>
							<li><a href="">Web Security</a></li>
							<li><a href="">AI and Machine Learning in Cybersecurity</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>INSA</h4>
						<ul>
							<li><a href="">Mentors</a></li>
							<li><a href="">awards</a></li>
							<li><a href="">Best Ethical hackers </a></li>
							<li><a href="">Info</a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4>Social media </h4>
						<ul>
							<li><a href="">YouTube</a></li>
							<li><a href="">Freelance</a></li>
							<li><a href="">Instagram</a></li>
							<li><a href="">Telegram</a></li>
							<li><a href="">Linked In</a></li>
					
						</ul>
					</div>
					<div class="widget-item">
						<h4>latest Cources</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">Subscribe</button>
							<p>*Get the latest Info by subscribing</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Register</a></li>
					<li><a href="#">Privacy</a></li>
				</ul>
				<div class="">
	Copyright &copy; Akrem <script>document.write(new Date().getFullYear());</script> All rights reserved.
</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

MesoOn/templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Contact</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search your course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Search Couse</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Get in started</h2>
            <p>The customer is very important, the customer will be followed by the customer. Until then, the greatest mauris of the world, but there was no official website. As well as legal wisdom.. </p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Your Name">
            <input type="text" placeholder="Your E-mail">
            <input type="text" placeholder="Subject">
            <textarea placeholder="Message"></textarea>
            <button class="site-btn">Sent Message</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Contact Info</h2>
            <p>Until then, the greatest mauris of the world, but there was no official website. As well as legal wisdom. He was suspended at the end of the course of the throat.</p>
          </div>
          <div class="phone-number">
            <span>Direct Line</span>
            <h2>+25180943465</h2>
          </div>
          <ul class="contact-list">
            <li>Addis Ababa bethel <br>Bole welosefer</li>
            <li>+25180943465</li>
            <li>coder.phyman@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

MesoOn/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      {% if request.user.is_authenticated %}
      <h2> {% if request.user.profile.is_teacher == True %}
         mentor
        {% endif %} {{ request.user.username|capfirst }}


      </h2>
      {% else %}
      <h2></h2>
      {% endif %}
      <p>.</p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="find related topic">
          <button type="submit" class="site-btn">Search</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="kurset">Basic Comprehensive Cybersecurity Courses</h2>
      <p>Discover a world of opportunity and security through our wide array of cybersecurity courses. Our curriculum is carefully crafted to equip you with the essential knowledge and skills needed to excel in this critical field. Here's what you can expect from our courses.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{{ cat.imazhi.url }}"></div>
          <div class="ci-text">

            <h5>{{cat.Title|capfirst}}</h5>

            <p>{{ cat.description|capfirst }}</p>
            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Look at the cases</a></span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
  <div class="container">
    <div class="section-title mb-0">
      <h2>Available basic cource</h2>
      <p class="pb-3">እነዚህ ለሳይበር ቡድኖች በእኛ ላይ የሚከተሏቸው አንዳንድ የሥልጠና ቪዲዮዎች ናቸው።.</p>
    </div>
  </div>
  <div class="course-warp">
    <div class="row course-items-area">
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 finance">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/3CaG2GI1kn0?controls=0"  frameborder="0" controls allowfullscreen></iframe>

          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>vurnerability</h5>
              <p>Hacking Tool</p>
              <div class="students">Course1</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Dejene, <span>mentors</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/Yftp2VA0hcM?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Defending</h5>
              <p>invention</p>
              <div class="students">Course2</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Dejene, <span>Mentors</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 web">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/dKzJ5ANLiIo?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Kali Linux</h5>
              <p>Hacking</p>
              <div class="students">course</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Dejene, <span>Mentors</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/ghkjm93LOag?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Cyber attack</h5>
              <p>Firewall</p>
              <div class="students">course4</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Dejene, <span>Mentors</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
<!-- course section end -->

{% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_teacher == True %}
<div class="container">
  <h1 class="text-center">መለያህ የmentor ፈቃድ አለው።</h1><br>
  <p class="text-center">By having a teacher account you now have fuller access to this platform. You can perform more functions than the initial student account. Some of these functions are:</p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
    <div class="col-md-4 text-center">
      <h3 class="p-4">can create your own class</h3>
      <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">create class</a>
    </div>
    <div class="col-md-8">
      <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
    </div>
  </div>

  <div data-aos="fade-left" class="row mt-4 mb-4 bg-light">
      <div class="col-md-8">
        <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
      </div>

    <div class="col-md-4 text-center">
      <h3 class="p-4">You can create your own content</h3>
      <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">create content</a>
  </div>
</div>

<div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
  <div class="col-md-4 text-center">
    <h3 class="p-4">You can upload your own lessons and videos..</h3>
    <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">create lesson</a>
  </div>
  <div class="col-md-8">
    <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
  </div>
</div>
</div>

{% else %}
<section data-aos="zoom-out" class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Register as mentor</h2>
            <p>To register as a mentor on the platform, you must complete the fields below and then you will have full access to upload courses and videos.</p>

          </div>
          <!-- signup form -->
          <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
            <input type="text" placeholder="your name" name="name">
            <input type="text" placeholder="Email" name="e-mail">
            <input type="text" placeholder="Phone number" name="phone">
            <button class="site-btn">Send the Request</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}

{% endblock content %}